### ISSUE TITLE
Different swipe-commands for Entries, Refereneces and ReadLater sections

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#10]
The list items of the Entries and References section allow a left-swipe gesture to show some commands on the an item. But bot show different commands:
- Entries: Share, Delete
- References: Edit, Share, Delete
- Read later: Save, Share, Delete

### Questions
- Why has Entries no Edit command?
- I would expect more consistency

**Comment by dankito** [comment]
- Why has Entries no Edit command?
Because Edit is the list item click action, so adding it here would be kind of redundant.

- I would expect more consistency
Do you think this is such a big issue? As different entities have different actions.
(And these are by the way also state dependent. E.g. a Reference has no url -> there's no Share action.)
I wouldn't know how to solve it otherwise to provide these action for the different kind of entities. I also think they are quite usefull so i'd like to provide them to the user.
Could you give me a hint how to solve it otherwise?

**Comment by dankito** [comment]
I asked now two other users and both said they don't mind this inconsistency.
As i also don't mind i will close this now.

**Comment by b3nk4n** [comment]
Haha, I'm a consistency nerd ... but I'm fine with wontfix.
Just wanted to mention it at least... ;-)
