### ISSUE TITLE
"New..." in an entry's reference is misleading and should be called "discard"

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#17]
For an entry, the user is able to add references. Within this reference page, there is a "New..." button (see [Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1NFR1UHN1WEhNOTA)), whose title/functionality is very misleading:

### Actual behavior
It clears all fields

### Expected behavior
- I thought it would show a popup/dialog to enter something (because "..." at the end usually indicates that an option follows another window or dialog)
- Regarding the functionality, the button should be called "Discard" or "Clear" (dt: Verwerfen)

**Comment by dankito** [comment]
The current behaviour is, behind the scenes it really drops the displayed reference and creates a new one, then displays it. Therefore all fields are cleared as the new reference does have no values yet.

But you're for sure right, for the user this is misleading.
Better i'd show a dialog 'Do you really want to discard the current and create a new reference?' to the user.

By the way, there's still a ToDo on my list to ask the user if she/he likes to save the current reference first when there are changes before switching to the new reference.

**Comment by dankito** [comment]
Implemented showing alert dialogs now. Will be part of next release.

**Comment by b3nk4n** [comment]
Ok, for me it looked like it simply cleared all inputs. With the dialog, it makes more sense now.

Btw: why is "FROM ISBN..." disabled? Is it an upcoming feature?

**Comment by b3nk4n** [comment]
Btw^2: how is "Use existing" working? When I try to enter the title of a reference of another entry/item, nothing shows up. What do I have to enter here? Looks like this is not self explaining... maybe an "android:hint" would be good here?

**Comment by dankito** [comment]
- Yes, 'FROM ISBN ...' is an upcoming feature. So ZXing will be there anyway * g * (so that's also when #21 gets tackled * g *)

- 'Use existing' i'm going to rename to 'Select existing'.
And yes, it should work the way you described: Entering some letters should find the reference you like.
But could be that due to updates in the index structure it's not fully working yet. Does it find your reference if you enter exactly the first letters of the first word of your reference's title?
After re-indexing the reference, e.g. making some changes and saving it, it should find it no matter which word of your reference's title (or publishing date or series of it) you enter.

**Comment by dankito** [comment]
Searching is working now.
