### ISSUE TITLE
Tapping the web content of an entry often opens the "Edit information" advanced editor

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#23]
When the user reads the web content and scrolls, the page automatically switches in a "fullscreen" mode. To exit this mode, the user has to tap on the content (and hopefully does not hit a link! :) ). But when he is tapping again somewhere in nowhere, he is not switching back into fullscreen mode, but opens the advanced text editor (which takes veeeeeery long to load for some websites!).

### Expected behavior
- I don't see a reason why a user would like to edit the web content (especially because editing the web content is very painful and slow)
- I would expect a tap switches back into fullscreen mode

**Comment by dankito** [comment]
- "I don't see a reason why a user would like to edit the web content"
I sometimes really do *g*. And friends of mine also do.
But usually you are in reader mode (the website mode is only there for legal reasons; or if the parsing result is crap) and there definitely  should be the option to edit the content / information. But this is only the minor issue (if the user wants it, go for it) ...

- "I would expect a tap switches back into fullscreen mode"
This is the major one. I'm also not very content with the current handling.
Before it was: Tapping enters / leaves fullscreen mode and there was an icon in the toolbar to edit entry's information.
My designer suggested we should start fullscreen mode by scrolling and use the tap to start editing, so that we can remove the icon from the toolbar (which is already very crowded yet).

So we either have to find another way to leave the fullscreen mode (preferable so that you can tap there without leaving it) or another way to enter edit mode. Good question.

**Comment by dankito** [comment]
What about adding a semi-transparent bar at the bottom of the fullscreen mode?
(+ some whitespace at end of web view's content so that the bar doesn't hide any content)

Next to the button to leave fullscreen mode i could place one to directly go to edit mode there.

**Comment by dankito** [comment]
We agreed now that entering / leaving fullscreen mode is done by a double tap.
So the user cannot anymore tap to leave fullscreen and accidentally going to edit mode as she/he thinks another tap re-enters fullscreen. 

The bar at the bottom will come soon.

**Comment by dankito** [comment]
Implemented the bar with button for exiting fullscreen mode as well.
Will close this issue now.

**Comment by b3nk4n** [comment]
I like the new behavior, but I still have one suggestion:

Since most websites are mostly white (white background), the light-gray button ([Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1YmFHWUM0T01taFE)) is hard to see at the very beginning. I took me some moments to realize there is a button.

**Proposed solution**
- Use the green accent color for the button
- Make it slightly transparent to see the content through it
