### ISSUE TITLE
AppBar and page title is usually at the top

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#24]
The AppBar, page title and the Back-button / Close-Button of DeepThough is located at the bottom of the app on every page (see [Screenshot](https://drive.google.com/open?id=0BxICpnwLMG_1U05ORDhnN3JVYTQ))
Almost every other app displays this at the top of the app. And personally, I think it would be better to have it at the top, because users are used to that.

Especially when the phone has a hardware buttom, it is awkward to have to Back-buttons next to each other. And having the "page title" at the bottom also feels a bit strange.

**Comment by dankito** [comment]
The two designers and i discussed about that and we all three agreed to place it at the bottom.
The reason is that on large screens it's really hard to reach the top of the screen with your thumb, see for example here: [https://static.lukew.com/large_smartphones1.png](url).

That's also the way Apple does it more and more and also Google starts to do it this way (e.g. Google Maps has the 'Hamburger icon' at the bottom left and the new Pixel 2 now also show the Google search bar at the bottom: [https://www.heise.de/newsticker/bilderstrecke/bilderstrecke_3849759.html?back=3849942](url)).

So we tried to place all important actions at the bottom of the screen tried to increase the usability of the app.

**Comment by b3nk4n** [comment]
Yes, most of your arguments are true.

But on the other side:
- The Chevron (back) button at the bottom is redundant, because
  - there is either a hardware-back button already
  - or a virtual (soft-key) back button
- It looks a bit odd with 2 back-buttons stacked on top of each other
- Users might be used to it?
- The title at the bottom is sometimes hidden by my left thumb (at least when holding the device with 2 hands) and I don't immediately get where I am right now 🗡 

But well, that's just my personal opinion ;-)

**Comment by dankito** [comment]
Also here, pros and cons for both sides * g *.
And you're right, having two back buttons stacked on each other (as least for devices having it's hard-/software back button an the right, there are some devices like Samsung ones having it on the left) also looks odd to me.
I'm leaving it there now, but in the future i might remove it in general or after the user got used to the concept that she/he can use it to abort editing.

By the way, did you see all the other changes i did to the toolbar?
- The toolbar is way smaller as it's actually indented (compare with app's main screen) to leave more room for the content
- It's back button is smaller
- There's less space between the title and the back button
- Also the toolbar has, depending on the screen width, a fixed maximum amount of icons (3 on a Moto G4, 2 on a Galaxy S2), but in my app all devices are showing up to 4 icons
