### ISSUE TITLE
Floating button close behavior on rotate / resume

### ISSUE THREAD

**Issue by b3nk4n** [dankito/DeepThought#32]
Minor issue, but the behavior of the floating buttons (open state when all items are shown) is different regarding app resume and screen rotate:

**Actual behavior**
- resume: buttons are still visible (open state)
- screen rotate: buttons not visible anymore (close state) because the activity get recreated

**Expected**
I personally would expect it the other way round:
- resume: closed
- screen rotate: still open

Or at least that is behaves the same: that the buttons are closed (not visible)

**Comment by dankito** [comment]
Absolutely true for the second case: After rotating screen the floating action button should be in the same state as before.

It just is impossible to distinguish in onResume() if onResume() has been called due screen rotation or if resuming activity otherwise. So don't know how to solve first case.

**Comment by dankito** [comment]
Fixed it, state will now get restored after rotating.
